version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /shortdb-operator
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /shortdb-operator
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /shortdb
    schedule:
      interval: daily
